### ISSUE TITLE
this.currentForm.id: Uncaught TypeError: string.replace is not a function

### ISSUE THREAD

**Issue by gvincent-equinoxx** [jquery-validation/jquery-validation#2527]
## Your environment
* Version of `jquery-validate`: 1.22.0
* Browser name and version: Edge 145.0.3800.58 (Windows Arm)

There appears to be a bug related to the reliance on `currentForm.id` to return the id attribute of the `<form>` element on [line 704](https://github.com/jquery-validation/jquery-validation/blob/3730881c9e587cb6e242617eb6846cc1e2fcc586/src/core.js#L704).

If there is a form element name `id` in the form, then the exposed property of the [form object for id is overwritten with the input element](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement#issues_with_naming_elements), not the string attribute value, leading to the type error. 

## Current behavior

If a form input with name = `id` is present in the form, a javascript error occurs and validation stops

## Expected behavior

Validation works independently of the names of the fields in the form element

## Live demo

https://codepen.io/gvincent-equinoxx/pen/vEKqEWw?
**Expected** console shows "submitted" and form does not submit
**Current** javascript hits error and so submit event is not caught - form submits and error shows in console: Uncaught TypeError: a.replace is not a function
